CREATE TABLE `orcamentos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`forma` varchar(20) NOT NULL,
	`tamanhoA` int NOT NULL,
	`tamanhoB` int,
	`pontos` int NOT NULL,
	`cores` int NOT NULL,
	`fixacao` varchar(20) NOT NULL,
	`maquina` varchar(20) NOT NULL,
	`materialBase` varchar(50) NOT NULL,
	`margemPercentual` int NOT NULL,
	`quantidade` int NOT NULL,
	`vendaOnline` int NOT NULL,
	`custoMateriais` int NOT NULL,
	`custoLinha` int NOT NULL,
	`custoEnergia` int NOT NULL,
	`custoPorPontos` int NOT NULL,
	`custoFixacaoAdicional` int NOT NULL,
	`custoTotalProducao` int NOT NULL,
	`precoFinalArredondado` int NOT NULL,
	`descontoAplicado` int NOT NULL,
	`precoUnitarioComDesconto` int NOT NULL,
	`precoTotal` int NOT NULL,
	`bastidorSugerido` varchar(100),
	`pecasPorBastidor` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `orcamentos_id` PRIMARY KEY(`id`)
);
