CREATE TABLE `itens_orcamento` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orcamento_id` int NOT NULL,
	`forma` varchar(20) NOT NULL,
	`tamanhoA` int NOT NULL,
	`tamanhoB` int,
	`pontos` int NOT NULL,
	`cores` int NOT NULL,
	`fixacao` varchar(20) NOT NULL,
	`maquina` varchar(20) NOT NULL,
	`materialBase` varchar(50) NOT NULL,
	`quantidade` int NOT NULL,
	`modoTrabalho` varchar(20) NOT NULL DEFAULT 'patches',
	`margemPerdaMaterial` int NOT NULL DEFAULT 0,
	`custoMateriais` int NOT NULL,
	`custoLinha` int NOT NULL,
	`custoEnergia` int NOT NULL,
	`custoPorPontos` int NOT NULL,
	`custoFixacaoAdicional` int NOT NULL,
	`custoTotalProducao` int NOT NULL,
	`precoUnitario` int NOT NULL,
	`precoTotal` int NOT NULL,
	`bastidorSugerido` varchar(50),
	`pecasPorBastidor` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `itens_orcamento_id` PRIMARY KEY(`id`)
);
